[[actions]]
name = "play"
path = "bin/spookyghost.exe"
platform = "windows"

[[actions]]
name = "play"
path = "SpookyGhost.app"
platform = "osx"

[[actions]]
name = "play"
path = "launch.sh"
platform = "linux"

[[prereqs]]
name = "vcredist-v14-x64"

[[actions]]
name = "manual"
path = "docs/documentation.html"
platform = "windows"

[[actions]]
name = "manual"
path = "SpookyGhost.app/Contents/Resources/docs/documentation.html"
platform = "osx"

[[actions]]
name = "manual"
path = "share/doc/spookyghost/documentation.html"
platform = "linux"

[[actions]]
name = "forums"
path = "https://encelo.itch.io/SpookyGhost/community"
